flask_app/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Titre', validators=[DataRequired()])
    content = TextAreaField('Contenu', validators=[DataRequired()])
    submit = SubmitField('Publier')

flask_app/main/routes.py
from flask import render_template, request, Blueprint
from flask_app.models import User, Post

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template("home.html", posts=posts)

@main.route("/about")
def about():
    return render_template("about.html", title="About")

flask_app/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_app import db
from flask_app.posts.forms import PostForm
from flask_app.models import Post
from flask_login import current_user, login_required

import os
import secrets

from PIL import Image

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()

    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Votre article a bien été créé et publié !', 'success')
        return redirect(url_for('main.home'))

    return render_template('create_post.html', title="Nouvel Article", form=form, legend='Créer un article')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)

    if post.author != current_user:
        abort(403)

    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Votre article a bien été modifié', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content

    return render_template('create_post.html', title='Modifier l\'article', form=form, legend='Modifier un article')


@posts.route("/post/<int:post_id>/delete", methods=['GET', 'POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)

    if post.author != current_user:
        abort(403)

    db.session.delete(post)
    db.session.commit()
    flash('Votre article a bien été supprimé.', 'success')
    return redirect(url_for('main.home'))

flask_app/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_app import db, bcrypt
from flask_app.users.forms import RegistrationForm, LoginForm, UpdateAccountForm
from flask_app.models import User, Post
from flask_login import login_user, current_user, logout_user, login_required
from flask_app.users.utils import save_picture

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
         return redirect(url_for('main.home'))

    form = RegistrationForm()
    if form.validate_on_submit():
         hash_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
         user = User(username=form.username.data, email=form.email.data, password=hash_password)
         db.session.add(user)
         db.session.commit()
         flash(f'Votre compte a bien été créé {form.username.data}! Vous pouvez à présent vous connecter', 'success')
         return redirect(url_for('users.login'))

    return render_template("register.html", title="Register", form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Erreur d\'authentification, Veuillez verifier votre e-mail ou votre mot de passe', 'danger')
    return render_template("login.html", title="Login", form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():

        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Vos informations ont bien été modifiées', 'success')
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template("account.html", title=f"{current_user.username}", image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)

flask_app/templates/about.html
{% extends "layout.html" %}
{% block content %}
    
    <div class="container pt-3">
        <h1>About Page</h1>
    </div>


{% endblock %}

flask_app/templates/account.html
{% extends "layout.html" %}
{% block content %}

    <div class="container pt-3">

        <img class="img-thumbnail" src="{{ image_file }}" alt="">
        <div>
            <h2>{{ current_user.username }}</h2>
            <small>{{ current_user.email }}</small>
        </div>

        <div class="form-container pt-3">
            <form action="" method="POST" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                <fieldset>
                    <legend>Informations personnelles</legend>
                    <div>
                        {{ form.username.label(class="") }}
                        {% if form.username.errors %}
                            {{ form.username(class="form-control col-md-6 is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                <small>
                                    {{ error }}
                                </small>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.username(class="form-control col-md-6") }}
                        {% endif %}
                    </div>
                    <div>
                        {{ form.email.label(class="") }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control col-md-6 is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <small>
                                        {{ error }}
                                    </small>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control col-md-6") }}
                        {% endif %}
                    </div>
                    <div>
                        {{ form.picture.label }}
                        {{ form.picture(class='form-control-file') }}
                        {% if form.picture.errors %}
                            {% for error in form.picture.errors %}
                                <span class="text-danger">{{ error }}</span>
                            {% endfor %}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="py-3">
                    {{ form.submit(class="btn btn-info")}}
                </div>
            </form>
        </div>

    </div>


{% endblock %}

flask_app/templates/create_post.html
{% extends "layout.html" %}
{% block content %}

    <div class="container pt-3">

        <div class="form-container">
            <form action="" method="POST">
                {{ form.hidden_tag() }}
                <fieldset>
                    <legend>{{ legend }}</legend>
                    <div class="form-group">
                        {{ form.title.label(class="") }}
                        {% if form.title.errors %}
                            {{ form.title(class="form-control col-md-6 is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.title.errors %}
                                    <small>
                                        {{ error }}
                                    </small>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.title(class="form-control col-md-6") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.content.label(class="") }}
                        {% if form.content.errors %}
                            {{ form.content(class="form-control col-md-6 is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.content.errors %}
                                    <small>
                                        {{ error }}
                                    </small>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.content(class="form-control col-md-6") }}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="py-3">
                    {{ form.submit(class="btn btn-info")}}
                </div>
            </form>
        </div>
    </div>


{% endblock %}

flask_app/templates/home.html
{% extends "layout.html" %}
{% block content %}

    <article class="container pt-3">

        <h1>Home Page</h1>

        {% for post in posts.items %}

            <section class="home-article-container">
                <div class="home-article-info-container">
                    <img src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" alt="{{ post.author.username + '-profile'}}">
                    <h2><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a> de <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a></h2>
                </div>

                <div class="home-article-content">
                    <small>{{ post.date_posted.strftime("%d %b %Y") }}</small>
                    <p>{{ post.content }}</p>
                </div>
            </section>

        {% endfor %}

        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if posts.page == page_num %}
                    <a class="paginate-btn btn btn-secondary" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                    <a class="paginate-btn btn btn-outline-secondary" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}

    </article>

{% endblock %}

flask_app/templates/layout.html
<!DOCTYPE html>
<html>
    <head>

        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">


        <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">

        {% if title %}
            <title> Flask Blog - {{ title }}</title>
        {% else %}
            <title> Flask Blog</title>
        {% endif %}

    </head>
    <body>

        <nav class="navbar navbar-expand-md navbar-dark bg-secondary">
            <div class="container">
                <a class="navbar-brand mr-4" href="/">Flask Blog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                        <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if current_user.is_authenticated %}
                            <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Profile</a>
                            <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">Create Post</a>
                            <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                        {% else %}
                            <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                            <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>

        {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        {% block content %}
        {% endblock %}

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>

    </body>
</html>

flask_app/templates/login.html
{% extends "layout.html" %}
{% block content %}

    <div class="container pt-3">

        <div class="form-container">
            <form action="" method="POST">
                {{ form.hidden_tag() }}
                <fieldset>
                    <legend>S'authentifier</legend>
                    <div class="form-group">
                        {{ form.email.label(class="") }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control col-md-6 is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <small>
                                        {{ error }}
                                    </small>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control col-md-6") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.password.label(class="") }}
                        {% if form.password.errors %}
                            {{ form.password(class="form-control col-md-6 is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <small>
                                        {{ error }}
                                    </small>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(class="form-control col-md-6") }}
                        {% endif %}
                    </div>
                    <div class="form-check">
                        {{ form.remember(class="form-check-input") }}
                        {{ form.remember.label(class="form-check-label") }}
                    </div>
                </fieldset>
                <div class="py-3">
                    {{ form.submit(class="btn btn-info")}}
                </div>
            </form>
        </div>

        <div>
            <small>
                Vous n'avez pas de compte ? <a href="{{ url_for('users.register') }}">S'enregistrer</a>
            </small>
        </div>

    </div>


{% endblock %}

flask_app/templates/post.html
{% extends "layout.html" %}
{% block content %}

    <article class="container article-detail-container pt-3">

        <header class="article-detail-header">
            <h1>{{ post.title }} <span class="article-detail-author">de <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a></span></h1>
            <small>{{ post.date_posted.strftime("%d %b %Y") }}</small>
        </header>

        <div class="article-detail-content">
            <p>{{ post.content }}</p>
        </div>

        {% if post.author == current_user %}
            <a class="btn btn-info" href="{{ url_for('posts.update_post', post_id=post.id) }}">Modifier l'article</a>
            <button class="btn btn-danger" type="button" data-toggle="modal" data-target="#deleteModal">Supprimer</button>
        {% endif %}

    </article>

    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Voulez-vous vraiment supprimer cet article ?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
            <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="post">
                <input class="btn btn-danger" type="submit" value="Supprimer">
            </form>
          </div>
        </div>
      </div>
    </div>

{% endblock %}

flask_app/templates/register.html
{% extends "layout.html" %}
{% block content %}

    <div class="form-container container pt-3">
        <form action="" method="POST">
            {{ form.hidden_tag() }}
            <fieldset>
                <legend>Rejoignez-nous Aujourd'hui !</legend>
                <div>
                    {{ form.username.label(class="") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control col-md-6 is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                            <small>
                                {{ error }}
                            </small>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control col-md-6") }}
                    {% endif %}
                </div>
                <div>
                    {{ form.email.label(class="") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control col-md-6 is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <small>
                                    {{ error }}
                                </small>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control col-md-6") }}
                    {% endif %}
                </div>
                <div>
                    {{ form.password.label(class="") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control col-md-6 is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <small>
                                    {{ error }}
                                </small>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control col-md-6") }}
                    {% endif %}
                </div>
                <div>
                    {{ form.confirm_password.label(class="") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control col-md-6 is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <small>
                                    {{ error }}
                                </small>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control col-md-6") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="py-3">
                {{ form.submit(class="btn btn-info")}}
            </div>
        </form>

        <small>
            Vous avez déjà un compte ? <a href="{{ url_for('users.login') }}">S'authentifier</a>
        </small>

    </div>

{% endblock %}

flask_app/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}

    <article class="container pt-3">

        <h1>Article de {{ user.username }} ({{ posts.total }})</h1>

        {% for post in posts.items %}

            <section class="home-article-container">
                <div class="home-article-info-container">
                    <img src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" alt="{{ post.author.username + '-profile'}}">
                    <h2><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a> de <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a></h2>
                </div>

                <div class="home-article-content">
                    <small>{{ post.date_posted.strftime("%d %b %Y") }}</small>
                    <p>{{ post.content }}</p>
                </div>
            </section>

        {% endfor %}

        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if posts.page == page_num %}
                    <a class="paginate-btn btn btn-secondary" href="{{ url_for('users.user_posts',username=user.username, page=page_num) }}">{{ page_num }}</a>
                {% else %}
                    <a class="paginate-btn btn btn-outline-secondary" href="{{ url_for('users.user_posts',username=user.username, page=page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}

    </article>

{% endblock %}